### PR TITLE
Add branch miss latency

### PR DESCRIPTION
**Pull request by kayeoc279**
Add branch miss penalty which shows U8 has 9 cycle miss penalty. F1->EX
refine parsing script

### CODE REVIEW

**Comment by virtualboots** [comment]
Does it work like you create 2 patterns: one always miss and another always hit. Then, the cycle difference is the miss prediction penalty?

Since both patterns seem not to repeat the branch instruction in a loop, how do you guarantee those branches are predicted to be taken or not taken?

**Comment by kayeoc279** [comment]
There are 5 function call in my test. The first four functions call(testfn and testfn1) are designed to train the branch predictor to predict not-taken no matter which branch we are going to execute. To achieve that testfn1 is designed to train all possible entries to predict not-taken.
The key here to guarantee that the fifth function call always predict wrong.
// always not taken
testfn(a,b,c);
testfn1(a,b);
testfn(a,b,c);
testfn1(a,b);

//always taken
testfn(a,b,c);

**Comment by kayeoc279** [comment]
The fun thing is that I can't use the cycle diff of 4th call and 5th call to calculate the branch miss penalty. Because there is or instruction that can be parallel execute with branch.
Why or instruction? Without or instructions the branch miss predict for 5th call can't be 100% miss predict. So the formula current using is that " 5th func call cycle / 64 (instructions) - 2 (one for branch one for or ). the or and branch need to be executed serial so that the cycle will be 2 here.

**Comment by kayeoc279** [comment]
some interesting expeiment: 
for 64 branch in testfn, back-to-back branch instruction actually get 75% miss predict rate.
But if you add one more instruction between branch the miss predict rate can be 100%.

**Pull request merged**
